### ISSUE TITLE
Feature 1: User can view list of zoo animals

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/AJAX-Project-0522#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view list of 10 zoo animals and click a button to view a new list of 10 zoo animals.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can see a list of 10 random zoo animals generated by zoo animal API, and they can click a button to refresh the list of animals to see a new list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/173161776-6b69d162-21b7-4ed0-8273-ddc04a126bcf.png)
![image](https://user-images.githubusercontent.com/96744088/173165216-fda546fa-132a-4c1c-a507-9fa207ea460f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create HTML frame with some dummy data that matches with the wireframe.
- [x] query the button 'Refresh Animals List'
- [x] listen for click event for 'Refresh Animals List' button, and create a function that renders the animal list.
- [x] create `<ul>` element and query the element.
- [x] create a DOM tree that renders the list of animals that matches the dummy data image style.
- [x] using the data from API, generate a list of animals with images and their names like wireframe.
- [x] go through the animal object data from API and call render function for each list.
- [x] append animal list to `<ul>` element
- [x] add conditional statement to button function to replace children of `<ul>`, for replacing animal list.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
