### ISSUE TITLE
Feature 2 : User can click animal to view details of zoo animal

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/AJAX-Project-0522#2]
## ⚙️ Feature

> ##### What capability will the users have when this feature is merged?

Users can click on animals to read more information about an animal such as diet, habitat, etc.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When an image of animal is clicked, it will show details of clicked animal with information about an animal. Users then can click on back to list button to go back to list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/173164893-b2f2c382-39df-454a-a12c-cbcc14b4a01c.png)
![image](https://user-images.githubusercontent.com/96744088/173165231-bee9ab2b-1bbb-4a66-bc00-e2c0a74282fa.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create an HTML skeleton with dummy data and add CSS styles that match the wireframe.
- [x] create a page that is responsive to different sizes of screens.
- [x] create a button that goes back to the list in `<footer>` section.
- [x] add data-view attribute to each container for main and details.
- [x] create view swapping function to switch views for switching detail view and main view.
- [x] when the view is changed to details view, hide the 'Refresh Animals List, and show 'back to list' button.
- [x] create a variable 'currentAnimalList' that holds list of current 10 animals.
- [x] add a click event to animal images, and:
  - [x] create a conditional statement that checks if the click target matches the IMG tag name and matches the animal name in the currentAnimalList.
  - [x] if matches, then execute the callback function below:
  - [x] for callback function, create a function that shows details of clicked animal.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
