### ISSUE TITLE
Feature 3 : User can add an animal to favorites page

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/AJAX-Project-0522#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add their favorite animal to favorites list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Users can click on a + button in information page of the animal to add that animal to favorites page. Users can decide if they want to add or cancel adding animal to favorites page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/173164970-cb50b7d6-6b65-4733-888f-440b3b7eacd2.png)
![image](https://user-images.githubusercontent.com/96744088/173165264-64f17d70-bd2e-4561-a2d8-ddc44c896fe8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create + button next to description in the information view.
- [x] create local storage for saving favorite animal in the favorites array.
- [x] create modal that matches with wireframe and appears when + button is clicked.
- [x] add functions to cancel and confirm buttons in the modal.
- [x] for confirm button function, add a feature that adds the current animal's data into data.favorites array.
- [x] double check if current animal data has been added to local storage.
- [x] add a feature to confirm button function that switches view back to main-list once current animal data is added.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
