### ISSUE TITLE
Feature 4 : User can view favorites page

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/AJAX-Project-0522#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view list of animals they added to favorites page.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on favorites button in the bottom of the main page to view the favorites page of saved animals.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/173165013-16ec6a2d-6934-4ef3-a9eb-c1b49a3e48ac.png)
![image](https://user-images.githubusercontent.com/96744088/173165287-99f25e62-7a46-459c-b65d-593a8f3ba9cb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create 'favorites' button in '<footer>' element.
- [x] create dummy data in HTML for favorites '<div data-view="favorites">' that match with wireframe.
- [x] check if the favorites page is responsive to different sizes of screen.
- [x] add a click handler to the 'favorites' button, and
  - [x] add a callback function that renders DOM tree for data from data.favorites array.
- [x] add a click handler to the 'go back to main' button; and add a function that changes the view to 'main-list'.
- [x] add a same click handler to button in the '<footer>' element.
- [x] when the view is changed, make sure that the buttons in the footer change.
- [x] check if a newly added favorite animal is added to the favorites page when confirmed added.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
