### ISSUE TITLE
Feature 5 : User can delete an animal from favorites page

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/AJAX-Project-0522#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can remove an animal from favorites page
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can click on delete button in the bottom of the each animal list in favorites page to delete the selected animal from favorites page.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96744088/173165157-46925019-e347-43f7-b33a-03f9697fe3f7.png)
![image](https://user-images.githubusercontent.com/96744088/173165190-7399cb9b-9379-44af-9f27-f9929c154c6f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add a delete button in the bottom of the description box in the favorites page.
- [x] add click handler to delete button, and
  - [x] make modal pop up
  - [x] change modal message to 'delete this animal?'
  - [x] change cancel button to delete button
- [x] remove animal from favorites page when delete button is clicked in the modal, and:
  - [x] hide modal.
  - [x] make sure that animal is deleted from local storage
  - [x] make sure that animal is deleted in the favorites page
- [x] hide modal if cancel button in the modal is clicked.
- [x] double check the functionality of delete feature.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
